language: clojure
lein: lein2
script: lein2 midje
matrix:
  include:
    - jdk: openjdk6
    - jdk: openjdk7
    - jdk: oraclejdk7
    - jdk: oraclejdk8
    - jdk: oraclejdk8
      env: OPTIMUS_JS_ENGINE=nashorn
